# Generated by Django 5.1.1 on 2024-09-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pimage',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.IntegerField(choices=[('1', 'Mobile'), ('2', 'Shoes'), ('3', 'Clothes')], verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nmae '),
        ),
        migrations.AlterField(
            model_name='products',
            name='pdetails',
            field=models.CharField(max_length=100, verbose_name='Product details'),
        ),
    ]
