# Generated by Django 5.1.1 on 2024-09-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoreapp', '0002_products_pimage_alter_products_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name '),
        ),
    ]
